name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Set up Endstone
        run: |
          python -m pip install --upgrade pip
          pip install endstone
          pip show endstone

      - name: Build Plugin
        run: |
          pip install pipx
          pipx run build --wheel

      - name: Test Plugin
        run: |
          mkdir -p bedrock_server/plugins
          cp -r dist/* bedrock_server/plugins
          echo Y | nohup python -m endstone > test.log 2>&1 &
          
          TIMEOUT=10
          INTERVAL=1
          TIME_PASSED=0
          while [[ $TIME_PASSED -lt $TIMEOUT ]]; do
            if cat test.log | grep -q "ERROR"; then
              echo "Plugin did not load correctly!"
              cat test.log
              exit 1
            fi
            sleep $INTERVAL
            TIME_PASSED=$((TIME_PASSED + INTERVAL))
          done
          
          echo "Plugin loaded successfully!"
          cat test.log
          exit 0

      - name: Upload Preview Build
        uses: actions/upload-artifact@v4
        with:
          name: endstone-music-player
          path: dist/
